# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
variables:
- name: BuildParameters.RestoreBuildProjects
  value: '**/*.csproj'
trigger:
- main
name: $(date:yyyyMMdd)$(rev:.r)
resources:
  repositories:
    - repository: self
      type: git
      ref: refs/heads/main
jobs:
  - job: Job_1
    displayName: CI 
    pool:
      vmImage: windows-latest
    steps:
      - checkout: self
        clean: true
      - task: UseDotNet@2
        displayName: Use .NET Core sdk 6.0.x
        inputs:
          version: 6.0.x
          includePreviewVersions: true
      - task: DotNetCoreCLI@2
        displayName: Build
        inputs:
          projects: $(BuildParameters.RestoreBuildProjects)
          arguments: --configuration $(BuildConfiguration)

